### ISSUE TITLE
Private state with Weakmaps?

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/extensible-web-report-card#24]
"Explaining the DOM via JavaScript"

Are weakmaps really the way of expressing private state?

**Comment by domenic** [comment]
They're semantically enough. Syntactically they're not pretty. But at least now we have a way to say "you can produce observable behavior that is equivalent to DOM objects, including private state" whereas before you just couldn't.

**Comment by travisleithead** [comment]
(Now that I understand WeakMaps better, this makes sense :)
